---
abstract: 'MARC validator plugins for the Czech National Library.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MARC-Validator-Plugin-NKC
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  English: 0
  Error::Pure::Utils: 0
  File::Share: 0
  MARC::Leader: 0.04
  MARC::Leader::Utils: 0
  MARC::Validator::Abstract: 0
  Perl6::Slurp: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/MARC-Validator-Plugin-NKC/issues
  homepage: https://github.com/michal-josef-spacek/MARC-Validator-Plugin-NKC
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/MARC-Validator-Plugin-NKC
version: '0.02'
