=pod

=encoding utf8

=head1 NAME

MARC::Validator::Plugin::NKC - MARC validator plugins for the Czech National Library.

=head1 REPOSITORY

L<https://github.com/michal-josef-spacek/MARC-Validator-Plugin-NKC>

=head1 AUTHOR

Michal Josef Špaček L<mailto:skim@cpan.org>

L<http://skim.cz>

=head1 LICENSE AND COPYRIGHT

© 2025 Michal Josef Špaček

BSD 2-Clause License

=head1 ACKNOWLEDGEMENTS

Development of this software has been made possible by institutional support
for the long-term strategic development of the National Library of the Czech
Republic as a research organization provided by the Ministry of Culture of
the Czech Republic (DKRVO 2024–2028), Area 11: Linked Open Data.

=head1 VERSION

0.03

=cut
